---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-thing-ts
  description: Test-thing
  annotations:
    github.com/project-slug: ServerlessOpsIO/test-thing-ts
spec:
  type: api
  lifecycle: production
  owner: group:backstage
  system: system:backstage
  providesApis:
    - resource:test-thing-ts

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-thing-ts
  description: |
    Thing API
    
    Manage things!
spec:
  type: openapi
  system: system:backstage
  lifecycle: production
  owner: group:backstage
  definition:
    $text: https://github.com/ServerlessOpsIO/test-thing-ts/blob/main/openapi.yaml
